### ISSUE TITLE
ZeeMarathi addon not working on Kodi 16

### ISSUE THREAD

**Issue by gpn002** [virajkanwade/plugin.video.zeemarathi#10]
Hi Viraj:
Thanks for suck a nice addon.
My parents are so harpy to watch all the Mearathi drama on this addon.
Unfortunately its not working since I have updated to Kodi-16.
I have kodi on 3-4 different devices (iPad, Mac, Windows and Apple TV), and none of it is able to play ZeeMarathi addon.
Could you please guide me to make it work?
Thanks

**Comment by virajkanwade** [comment]
Kodi update didn't break it. Right at the same time, zee moved to ozee.com for videos which is blocked here. So I cannot fix it.
