### ISSUE TITLE
plugin broken; may be need to change the url

### ISSUE THREAD

**Issue by samjoandco** [virajkanwade/plugin.video.zeemarathi#3]
I am not sure if this is the place to report errors, please correct as necessary.
may be the url has changed; not sure. here is the working url as seen in browser 

http://zeeapp4-vh.akamaihd.net/i/draco//shows/Zee_Marathi/Chala_Hawa_Yeu_Dya/September/22092015/Chala_Hawa_Yeu_Dya_Episode_116.smil/master.m3u8?key1=dittotv.com&hdnea=st=1443366902~exp=1443368402~acl=*~hmac=1cdeb3dc35819df69e7c16f91b6d7ad76b486c98810dc8e1dd7ed272cafb5252

here is the log:
08:42:25 T:3040952320  NOTICE: DVDPlayer: Opening: http://dittotv3-vh.akamaihd.net/i/draco/shows/Zee_Marathi/Chala_Hawa_Yeu_Dya/September/22092015/Chala_Hawa_Yeu_Dya_Episode_116.smil/master.m3u8?key1=www.zeemarathi.com&hdnea=st=1443368016~exp=1443369216~acl=*~hmac=07f61fa272da37e12f79853d1d0aafeb62d5ad9cd2cff20da5c45c4eb16db6f3
08:42:25 T:3040952320 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
08:42:26 T:2896655424   ERROR: OpenDemuxStream - Error creating demuxer
08:42:26 T:3040952320   ERROR: Playlist Player: skipping unplayable item: 0, path [http://dittotv3-vh.akamaihd.net/i/draco/shows/Zee_Marathi/Chala_Hawa_Yeu_Dya/September/22092015/Chala_Hawa_Yeu_Dya_Episode_116.smil/master.m3u8?key1=www.zeemarathi.com&hdnea=st=1443368016~exp=1443369216~acl=*~hmac=07f61fa272da37e12f79853d1d0aafeb62d5ad9cd2cff20da5c45c4eb16db6f3]

**Comment by virajkanwade** [comment]
Works for me. Are you using Kodi 14 (helix). There is some bug with curl where requests sometime fail. Restart kodi and try again.

**Comment by samjoandco** [comment]
i am using Kodi isengard openelec 5.95.5
this was working earlier but has been failing consistently for last 2 weeks.

**Comment by virajkanwade** [comment]
Thats a beta build. Unfortunately don't have the bandwidth to support beta
builds.

**Comment by virajkanwade** [comment]
Tested it right now on openelec 5.0.8 helix and mac osx isengard and worked
for me.

**Comment by samjoandco** [comment]
got it; 
i will downgrade and check if it works on 5.0.8

**Comment by samjoandco** [comment]
Hey Viraj
can you help me on how to get this url working?
I am trying to stream the Events from Zee Marathi
home <http://www.zeemarathi.com/> » events
<http://www.zeemarathi.com/events> » Zee Marathi Awards 2014

curl "
http://dittotv-vh.akamaihd.net/i/draco/shows/Zee_Marathi/Zee_Marathi_Awards_2014/October/26102014/Zee_Marathi_Awards_2014_Episode_1.smil/master.m3u8?key1=www.zeemarathi.com&hdnea=st=1446829927~exp=1446831127~acl=*~hmac=e091b83dadc422f21e987815aeb70ac2b5436537a51898cbf3166512f1f83f5e"
-H "Host: dittotv-vh.akamaihd.net" -H "User-Agent: Mozilla/5.0 (Windows NT
10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0" -H "Accept:
text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" -H
"Accept-Language: en-US,en;q=0.5" --compressed -H "Referer:
http://www.zeemarathi.com/sites/all/modules/gec_videos/jwplayer12/jwplayer.flash.swf"
-H "Connection: keep-alive"

**Comment by virajkanwade** [comment]
Unfortunately Zee has sent out a Infringement Notice WRT Copyright (which
makes no sense at all, since the addon just acts like a browser). So I am
not actively working on the addon as of now.

On Fri, Nov 6, 2015 at 9:18 AM, samjoandco <notifications@github.com> wrote:

> Hey Viraj
> can you help me on how to get this url working?
> I am trying to stream the Events from Zee Marathi
> home <http://www.zeemarathi.com/> » events
> <http://www.zeemarathi.com/events> » Zee Marathi Awards 2014
>
> curl "
>
> http://dittotv-vh.akamaihd.net/i/draco/shows/Zee_Marathi/Zee_Marathi_Awards_2014/October/26102014/Zee_Marathi_Awards_2014_Episode_1.smil/master.m3u8?key1=www.zeemarathi.com&hdnea=st=1446829927~exp=1446831127~acl=*~hmac=e091b83dadc422f21e987815aeb70ac2b5436537a51898cbf3166512f1f83f5e
> "
> -H "Host: dittotv-vh.akamaihd.net" -H "User-Agent: Mozilla/5.0 (Windows NT
> 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0" -H "Accept:
> text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" -H
> "Accept-Language: en-US,en;q=0.5" --compressed -H "Referer:
>
> http://www.zeemarathi.com/sites/all/modules/gec_videos/jwplayer12/jwplayer.flash.swf
> "
> -H "Connection: keep-alive"
>
>
> On Sun, Sep 27, 2015 at 10:03 AM, Viraj Kanwade <notifications@github.com>
> wrote:
>
> > Tested it right now on openelec 5.0.8 helix and mac osx isengard and
> worked
> > for me.
> >
> > On Sep 27, 2015 10:01 AM, "V'Raj Kanwade" <viraj.kanwade@gmail.com>
> wrote:
> >
> > > Thats a beta build. Unfortunately don't have the bandwidth to support
> > beta
> > > builds.
> > > On Sep 27, 2015 9:57 AM, "samjoandco" <notifications@github.com>
> wrote:
> > >
> > >> i am using Kodi isengard openelec 5.95.5
> > >> this was working earlier but has been failing consistently for last 2
> > >> weeks.
> > >>
> > >> —
> > >> Reply to this email directly or view it on GitHub
> > >> <
> >
> https://github.com/virajkanwade/plugin.video.zeemarathi/issues/3#issuecomment-143576838
> > >
> > >> .
> > >>
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/virajkanwade/plugin.video.zeemarathi/issues/3#issuecomment-143577356
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/virajkanwade/plugin.video.zeemarathi/issues/3#issuecomment-154476841>
> .
>



-- 
"Human knowledge belongs to the world!" - Antitrust

**Comment by samjoandco** [comment]
ok, thx
