### ISSUE TITLE
zee marathi plugin not working for last 1 week

### ISSUE THREAD

**Issue by rp1313** [virajkanwade/plugin.video.zeemarathi#4]
Thank you for writing this plugin. 
could you please help. i am attaching the kodi debug log link to our issue 
http://xbmclogs.com/pbtae29oi
could you kindly help?
Regards,
Rajesh

**Comment by virajkanwade** [comment]
What version of Kodi are you using? From the logs the video file received 403 Forbidden. But it works for me.I tried it on Kodi Isengard on Mac.

**Comment by rp1313** [comment]
10:54:08 T:1789673176  NOTICE: Starting Kodi (15.2-RC1 Git:2015-08-28-59716ca). Platform: Android ARM 32-bit
10:54:08 T:1789673176  NOTICE: Using Release Kodi x32 build
10:54:08 T:1789673176  NOTICE: Kodi compiled Aug 28 2015 by GCC 4.8.0 for Android ARM 32-bit API level 17 (API level 17)
10:54:08 T:1789673176  NOTICE: Running on MBX M8S with Android 4.4.2 API level 19, kernel: Linux ARM 32-bit version 3.10.33
10:54:08 T:1789673176  NOTICE: FFmpeg version: 2.6.4-kodi-2.6.4-Isengard
10:54:08 T:1789673176  NOTICE: Host CPU: ARMv7 Processor rev 1 (v7l), 2 cores available
10:54:08 T:1789673176  NOTICE: Product: n200, Device: n200, Board: n200 - Manufacturer: MBX, Brand: MBX, Model: M8S, Hardware: amlogic
10:54:08 T:1789673176  NOTICE: External storage path = /storage/emulated/0; status = ok
10:54:08 T:1789673176  NOTICE: ARM Features: Neon enabled
10:54:08 T:1789673176  NOTICE: special://xbmc/ is mapped to: /data/data/org.xbmc.kodi/cache/apk/assets
10:54:08 T:1789673176  NOTICE: special://xbmcbin/ is mapped to: /data/data/org.xbmc.kodi/cache/apk/assets
10:54:08 T:1789673176  NOTICE: special://masterprofile/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata
10:54:08 T:1789673176  NOTICE: special://home/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi
10:54:08 T:1789673176  NOTICE: special://temp/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp
10:54:08 T:1789673176  NOTICE: The executable running is:
10:54:08 T:1789673176  NOTICE: Local hostname: localhost
10:54:08 T:1789673176  NOTICE: Log File is located: /storage/emulated/0/And

this is on a android device. running on the following
GooBang Doo M8S TV Box Amlogic S812 Quad
Core Fully loaded Add-ons and KODI Google Android 4.4.2 Kitkat H.265
Airplay Miracast 3D [ASIN: B013NGP51Q]

thank you in advance for your time

**Comment by virajkanwade** [comment]
You are using 15.2-RC1, a release candidate. Unfortunately don't have the bandwidth to support non-stable Kodi. See similar issue #3

**Comment by virajkanwade** [comment]
Current stable release is 15.1 http://kodi.tv/download/

**Comment by rp1313** [comment]
yes we downloaded and installed again. it is same error.

**Comment by virajkanwade** [comment]
Can you check if the video works directly from your device browser?

http://www.zeemarathi.com/shows/nanda-saukhya-bhare/video/nanda-saukhya-bhare-episode-75-october-12-2015-full-episode.html

On Mon, Oct 12, 2015 at 9:58 PM, rp1313 <notifications@github.com> wrote:

> yes we downloaded and installed again. it is same error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/virajkanwade/plugin.video.zeemarathi/issues/4#issuecomment-147601525>
> .
>



-- 
"Human knowledge belongs to the world!" - Antitrust

**Comment by virajkanwade** [comment]
From #5:
can you tell us how to install previous version of the plugin. seems like after the pagination android is broken. on 15.1 also we installed 15.1 as you suggested but is still the same issue. 
Thank you very much in advance for your help. we really like to watch the marathi serials. and will really appreciate your help on this.
rajesh

**Comment by virajkanwade** [comment]
Not sure how Kodi works on android. Anyways, even if you install previous version of the plugin, kodi will auto update it. 

1. Did the video work in browser directly from ZeeMarathi website? ZeeMarathi might have added region access control blocking the video in your region.
2. Are all videos not working? Its possible that only the latest video is not working.

**Comment by virajkanwade** [comment]
Anyways pagination was added on Aug 22. And you said its not working since last 1 week.

**Comment by virajkanwade** [comment]
Just installed Kodi (https://play.google.com/store/apps/details?id=org.xbmc.kodi&hl=en) Installed ZeeMarathi and tested the same video and it worked. So not sure how else to help you.

Got to System > System Info and confirm it says Kodi 15.1 Git:2015-08-22-234ccf8
