### ISSUE TITLE
zee marathi add on not working Jarvis 16.0

### ISSUE THREAD

**Issue by prinzen150** [virajkanwade/plugin.video.zeemarathi#9]
Hello,
I m using Kodi Jarvis version 16.0 and Zee marathi addon 0.5. 
for the last 2 weeks i am receiving a log script error when running any shows from Zee Marathi
Can you please help ?

**Comment by rahulkashikar** [comment]
Mr Viraj, the developer only can fix it. I am also facing the same. I think site changed a bit which makes our python unable to parse it properly.

**Comment by virajkanwade** [comment]
Unfortunately, zee marathi has added some security and now shows videos through ozee.com. The video urls are no longer available. Also, they seem to have added region restrictions. So don't think I can make it work as of now.
